# Importar bibliotecas

In [1]:
from numpy import array
#Solo se manda a llamar una parte de la biblioteca

arr = array([1, 2, 3, 4, 5])#Crear arreglo
print(arr)

[1 2 3 4 5]


In [2]:
import numpy 
#Importar toda la biblioteca

arr = numpy.array([1, 2, 3, 4, 5])#Como parámetro recibe una lista o tupla. Pueden ser anidadas.
print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np
#Se hace uso de un alias

arr = np.array([1, 2, 3, 4, 5])
print(arr)

print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [35]:
#Creando arreglos de varias dimensiones
cero = np.array(42) #Cero
uno = np.array([1, 2, 3, 4, 5]) #Uno
dos = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #Dos
tres = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #Tres

#Imprimir dimensiones
print(cero.ndim)
print(uno.ndim)
print(dos.ndim)
print(tres.ndim)

#Creando arreglos de n dimensión
cinco = np.array([1,2,3,4], ndmin = 5)
print(cinco)

0
1
2
3
[[[[[1 2 3 4]]]]]


In [22]:
#Accediendo a elementos
print(uno[0])
print(dos[1,0])
print(tres[0,1,1])

#Acceder a un rango de datos
print(uno[1:4]) #El primero se incluye y el segundo se excluye
print(uno[1:]) #Hasta el final
print(uno[:4]) #Desde el principio
print(uno[-3:-1])
print(uno[1:4:2])

print(dos[0,1:])
print(dos[0:2, 1])

1
4
5
[2 3 4]
[2 3 4 5]
[1 2 3 4]
[3 4]
[2 4]
[2 3]
[2 5]


In [28]:
cadena = np.array(['lechuga','espinaca','brocolí'])
print(cadena.dtype)

flotante = np.array([4.5534, 6.5435, 4566.3322])
print(flotante.dtype)

cadena = np.array([1, 2, 3, 4], dtype='f')
print(cadena.dtype)

<U8
float64
float32


In [32]:
#Método astype()
entero = flotante.astype(int) #('i')
print(entero)

[   4    6 4566]


In [33]:
#Copiar copy()
copia = entero.copy()
copia[0] = 10000

print(copia)
print(entero)

[10000     6  4566]
[   4    6 4566]


In [43]:
print(dos.shape) #Forma 
print(dos.size) #Tamaño

print(tres.shape)

#Reshape() cambiar la forma
arreglo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
nuevo_arr = arreglo.reshape(4,3)
nuevo_arr[0,0] = 10000

print(arreglo)
print(nuevo_arr)

(3, 3)
9
(2, 2, 3)
[10000     2     3     4     5     6     7     8     9    10    11    12]
[[10000     2     3]
 [    4     5     6]
 [    7     8     9]
 [   10    11    12]]


In [49]:
#Iterando arreglos
arreglo = np.array([1,2,3])

for x in arreglo:
  print(x)

arreglo = np.array([[1,2],[3,4]])
for x in arreglo:
  for y in x:
    print(y)

#nditer() Iterador n dimensiones
for x in np.nditer(arreglo):
  print(x)

1
2
3
1
2
3
4
1
2
3
4


Métodos de Numpy

In [52]:
#hstack() y vstack()  
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
horizontal = np.hstack((arr1,arr2))
vertical = np.vstack((arr1,arr2))

print(horizontal)
print(vertical)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [91]:
from numpy import random #Aleatorio

x = random.randint(100)#Entero
print(x)

x = random.rand(3,3)#Float
print(x)

x = random.randint(100, size = (5,5))
print(x)

90
[[0.56390647 0.18427955 0.63854346]
 [0.34153506 0.98266209 0.39035568]
 [0.18386205 0.92104437 0.95683752]]
[[91 58 72 41 41]
 [31 81 79 65 18]
 [79 54 72 35 69]
 [47  5 86 47 35]
 [45 76 76 92 83]]


In [96]:
#Arange
arr1 = np.arange(5,16,2)#Inicio, fin, paso
print(arr1)

#Linspace
arr = np.linspace(10,20, num=3)#Inicio, fin, división
print(arr)

#Mean
media = np.mean(x)
print(media)

#Sum
suma = np.sum(x)
print(suma)

#Ones (Unos)
arr = np.ones((3,3), dtype=int)
print(arr)

#Zeros (Ceros)
arr = np.zeros((4,4), dtype=int)
print(arr)

#Sqrt (Square root = raíz cuadrada)
arr = np.array([4,9,16])
raiz = np.sqrt(arr)
print(raiz)

#Empty
arr = np.empty([2,2], dtype=int)
print(arr)

#Full
arr = np.full((3,3), [1,2,3])
print(arr)

#Max y min
maximo = np.amax(x)
minimo = np.amin(x)
print(maximo)
print(minimo)

[ 5  7  9 11 13 15]
[10. 15. 20.]
59.12
1478
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[2. 3. 4.]
[[0 1]
 [0 0]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
92
5
